name: swinunetr
object:
  _target_: models.swinunetr.SwinUNETR
  model_name: ${model_name}
  spatial_dims: ${spatial_dims}
  feature_size: ${feature_size}
  in_channels: ${in_channels}
  classes: ${classes}
  drop_rate: ${drop_rate}
  norm_name: ${norm_name}
  use_checkpoint: ${use_checkpoint}
