name: unet
object:
  _target_: models.unet.UNet
  model_name: ${model_name}
  spatial_dims: ${spatial_dims}
  in_channels: ${in_channels}
  classes: ${classes}
  channels: ${channels}
  strides: ${strides}
  num_res_units: ${num_res_units}
  norm: ${norm}
  activation: ${activation} 
  dropout: ${dropout}
  bias: ${bias}
  # deep_supervision: ${deep_supervision}
