defaults:
  - model: segresnet
  - optimizer: adamw
  - scheduler: cosine
  - _self_
  
run_name: ${model.object.model_name}
config_name: config_segresnet.yaml

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  max_epochs: 1
  log_every_n_steps: 10000000000
  check_val_every_n_epoch: 1
  deterministic: warn

criterion:
  _target_: monai.losses.DiceCELoss
  include_background: True
  sigmoid: True

model_name: config_segresnet
spatial_dims: 2
init_filters: 32
in_channels: 3
classes: 1
dropout_prob: 0.1
norm: 'batch'

img_size: 512
batch_size: 16
lr: 1e-4


# Use if you want to sweep over multiple models
# hydra:
#   sweeper:
#     params:
#       batch_size: 1,2,4,8
