defaults:
  - model: attention_unet
  - optimizer: adamw
  - scheduler: cosine
  - _self_
  
run_name: ${model.object.model_name}
config_name: config_attention_unet.yaml

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  max_epochs: 1
  log_every_n_steps: 10000000000
  check_val_every_n_epoch: 1
  deterministic: warn

criterion:
  _target_: monai.losses.DiceCELoss
  include_background: True
  sigmoid: True

model_name: attention_unet
spatial_dims: 2
in_channels: 3
classes: 1
channels: [64, 128, 256, 512, 1024]
strides: [2, 2, 2, 2] 
dropout: 0.2
img_size: 512
batch_size: 16
lr: 1e-4


# Use if you want to sweep over multiple models
# hydra:
#   sweeper:
#     params:
#       batch_size: 1,2,4,8
