defaults:
  - model: unet
  - optimizer: adamw
  - scheduler: cosine
  - _self_
  
run_name: ${model.object.model_name}

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  max_epochs: 300
  log_every_n_steps: 10000000000
  check_val_every_n_epoch: 1
  deterministic: warn

criterion:
  _target_: monai.losses.DiceCELoss
  include_background: True
  sigmoid: True

model_name: unet
spatial_dims: 2
in_channels: 3
classes: 1
channels: [64, 128, 256, 512, 1024]
strides: [2, 2, 2, 2] 
num_res_units: 0
norm: 'batch'
activation: 'relu'
dropout: 0.1
bias: False
img_size: 512
batch_size: 16
lr: 1e-4


# Use if you want to sweep over multiple models
# hydra:
#   sweeper:
#     params:
#       batch_size: 1,2,4,8
