defaults:
  - model: swinunetr
  - optimizer: adamw
  - scheduler: cosine
  - _self_
  
run_name: ${model.object.model_name}
config_name: config_swinunetr.yaml

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  max_epochs: 300
  log_every_n_steps: 10000000000
  check_val_every_n_epoch: 1
  deterministic: warn

criterion:
  _target_: monai.losses.DiceCELoss
  include_background: True
  sigmoid: True

model_name: swinunetr
spatial_dims: 2
in_channels: 3
classes: 1
feature_size: 48
drop_rate: 0.1
norm_name: batch
use_checkpoint: True

img_size: 512
batch_size: 16
lr: 1e-4

# Use if you want to sweep over multiple models
# hydra:
#   sweeper:
#     params:
#       batch_size: 1,2,4,8
