defaults:
  - model: unet
  - optimizer: adamw
  - scheduler: null
  - _self_
  
run_name: unet

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  max_epochs: 300
  log_every_n_steps: 5
  deterministic: warn

criterion:
  _target_: monai.losses.DiceCELoss
  include_background: True
  sigmoid: True

img_size: 224  # Fixed image size for UNet
batch_size: 1
lr: 1e-3

# Use if you want to sweep over multiple models
# hydra:
#   sweeper:
#     params:
#       batch_size: 1,2,4,8
